---
name: Ports and Adapters DDD Architecture
applications:
- name: domain
  group: component-internal-bounded-context
  description: Core Domain logic
  provided-services:
  - name: domain-objects
    type: inbound-port
  - name: repository-interfaces
    type: outbound-port
  - name: eventpublish-interfaces
    type: outbound-port
- name: application
  group: component-internal-bounded-context
  description: Application Use Cases
  provided-services:
  - name: application-services
    type: inbound-port
    description: Main Application API. Also internaly works with eventpublish-interfaces
    dependencies:
    - reference: domain.domain-objects
    - reference: domain.repository-interfaces
      relationship: uses
  - name: eventpublish-interfaces
    type: outbound-port
  - name: domainEventAdapter
    type: "(logic)"
    description: Listen for (some) domain events. Also internaly works with eventpublish-interfaces
    dependencies:
    - reference: domain.eventpublish-interfaces
      relationship: implements
