name: dependency security scanning

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  frontend:
    name: Frontend NPM dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: cd controller/web/template && npm ci
      - uses: oke-py/npm-audit-action@v1.7.1
        with:
          audit_level: moderate
          working_directory: controller/web/template/
          production_flag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: nxpthx,bike
          issue_labels: vulnerability,test
          dedupe_issues: true
  golang:
    name: GOlang backend dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x in order to write go.list file
        uses: actions/setup-go@v2
        with:
         go-version: ^1.15
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@1.0.1
